### ISSUE TITLE
shiboken2 lässt sich nicht installieren

### ISSUE THREAD

**Issue by Dennion** [H3c702/Hector9000#20]
Mahlzeit,

leider habt ihr in eurer `requirements.txt` noch folgendes Modul drin:

`shiboken2==5.12.1`

diesen lässt sich aber nichtmehr installieren und führt dadurch bei vielen Nutzern zu Fehler in der setup.py

Grüße,
Dennion

**Comment by DevTown** [comment]
What Pythonversion are you using ?

**Comment by Dennion** [comment]
Hey,

> Python 3.7.3

There is also a problem with Enum. I have already noticed 3 users including me with whom the module Enum is not installed or can be installed.

Greets,
Dennion

**Comment by DevTown** [comment]
Ok the Enum is gone where I am working on. The rest ist will test. 
I am using pythn 3.6 atm but I will do  tests with 3.7 and 3.8.

**Comment by DevTown** [comment]
So I have fixed the problems in my workingcopy. So I am looking for the weekend for a merge.

**Comment by Mugel8045** [comment]
​Hi DevTown, I don´t want to bother you, but I need the new Software, because the hardware is ready and I want to test it.

Thanks


Anian

**Comment by DevTown** [comment]
If you cant wait you can use the MoveToDB Branch : https://github.com/H3c702/Hector9000/tree/MoveToDB

At the moment I cant say when it will be merged. Lots of work todo.

**Comment by MauriceDe** [comment]
Hallo zusammen,

hat die Installation über den MoveToDB Branch bei jemandem funktioniert?
Ich bekomme hier auch die Fehlermeldung das shiboken2 nicht installiert werden kann.

Vielen Dank + Viele Grüße
Maurice

**Comment by DevTown** [comment]
https://travis-ci.org/github/H3c702/Hector9000/builds/665318311?utm_source=github_status&utm_medium=notification
Here  the installation will be testet for div. python versions. 

Can you post the requirements.txt plz that you are using?

**Comment by MauriceDe** [comment]
Hi DevTown,
thanks for the fast respond.
I'm using this requirements.txt:
Adafruit-GPIO==1.0.3
Adafruit-PCA9685==1.0.1
Adafruit-PureIO==1.0.4
atomicwrites==1.3.0
attrs==19.1.0
board==0.0.0.post0
certifi==2018.11.29
chardet==3.0.4
docutils==0.14
idna==2.8
more-itertools==7.0.0
packaging==19.0
paho-mqtt==1.5.0
pluggy==0.12.0
py==1.8.0
Pygments==2.3.1
pyparsing==2.4.0
pytest==5.4.1
requests==2.21.0
shiboken2==5.14.1
six==1.12.0
spidev==3.2
urllib3==1.24.1
wcwidth==0.1.7
webcolors==1.3
zipp==3.1.0

the following error message appears:
Could not find a version that satisfies the requirement shiboken2==5.14.1 (from -r requirements.txt (line 20)) (from versions: )
No matching distribution found for shiboken2==5.14.1 (from -r requirements.txt (line 20))

**Comment by DevTown** [comment]
Ok it seams that the shiboken2 do not hold older versions. So shiboken2 is not a direct ref I throw it out of the req. My tests went green. so could you test it on your side plz ? Just delete the line of shiboken2 and test again.

**Comment by MauriceDe** [comment]
ok, I delete the line of shiboken2.
After I installed the following packages all modules were loaded:
pip3 install paho-mqtt
pip3 install board
pip3 install adafruit-circuitpython-neopixel

"import Enum" I have replaced with "from enum import Enum".

After executing ./start.sh nothing happens. The directory "srv" with the file "main.py" described in the Readme is missing.

Is this due to an error from start.sh or has nothing to do with it

Thanks a lot

**Comment by schuetzi99** [comment]
You can also take a look at my branch "charles-new", which is a fork of MoveToDB.
I'm not a developer. My knowledge of Python is small, and since the using of MQTT the code is very complex for me, so I guess I can't be a great help for DevTown here. Nevertheless my hardware is running with that branch, and in my opinion more stable as with the stable code.
By the way, some parts of my hardware are a bit different, so I had to do some changes regarding hardware.

**Comment by MauriceDe** [comment]
@DevTown Thanks for the hint!
I have completely reinstalled the Raspian. Then do the following:

sudo apt-get update
sudo apt-get upgrade
git clone --depth=50 --branch=MoveToDB https://github.com/H3c702/Hector9000.git H3c702/Hector9000
cd H3c702/Hector9000
git checkout -qf 90517dfdcf84ffef5429ee3d8cf614a95e820445
sudo apt-get install virtualenv 
sudo apt-get install python3-venv
virtualenv /home/pi/hector-venv-37 -p python3.7
source ~/hector-venv-37/bin/activate
python --version
pip --version
sudo apt-get -y install mosquitto
pip install -r requirements.txt (shiboken2 commented out)
cd src
python -m pytest

============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.4.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/pi/H3c702/Hector9000/src
collected 21 items                                                             

tests/test_HectorController.py ..                                        [  9%]
tests/test_HectorSimulator.py .......                                    [ 42%]
tests/test_database.py ............                                      [100%]

sudo apt-get install mosquitto-clients
sudo ./start.sh

Could it be that I have to install a few modules or adjust the paths?
How can I start the actual software in this branch?

Sorry I haven't done that much with python yet.
Thanks for your support!

**Comment by DevTown** [comment]
why you do : git checkout -qf 90517df ? 
And why you use a venv on the pi?

for installation have a look at setup.sh. 

If you have any defined problems (in your post I cant sea any) plz open a new issue. 
This I will close because the topic is fixed.
