### ISSUE TITLE
Problem with Stepmotors

### ISSUE THREAD

**Issue by Dennion** [H3c702/Hector9000#21]
Heyho,

i have a Problem with my step motor in den Last Release Version. The step motor just jerks back and forth instead of moving in and out properly. It is also relatively loud in the latest version. But only there. 

Greets,
Dennion

**Comment by Dennion** [comment]
Hey, i habe found a user with the same problem.

**Comment by DevTown** [comment]
Quite more infos could held. Python version, Stepper motor version , Hardware ....

**Comment by Dennion** [comment]
Heyho,
Python3 Version: 3.7.3
-----
Stepper Motor Driver: Allegro A4988 (https://www.amazon.de/gp/product/B01MDNY71E/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1)
-----
Stepper Motor: Schrittmotor Nema 17 1.5A 17HS4401 (https://www.amazon.de/gp/product/B07GLMGQB3/ref=ppx_yo_dt_b_asin_title_o01_s02?ie=UTF8&psc=1)
-----
Hector9000: master 
-----
Pinout: Wie im Handbuch

Fehlt noch was?

**Comment by Dennion** [comment]
Hey, ich habe auch nochmal ein Video bezüglich des Problems hochgeladen. 

https://youtu.be/fEPw5D4FT5E

**Comment by DevTown** [comment]
Hi, did you tune the Drivers to the correct voltage for this motors? I am pretty sure, that we did not change anything with the stepper in the release.

**Comment by Dennion** [comment]
Hey, yes a have tryit in Arduino with this Code:

`int stepCounter;
int steps = 200;

void setup()
{
pinMode(6, OUTPUT); // Enable
pinMode(5, OUTPUT); // Step
pinMode(4, OUTPUT); // Richtung

digitalWrite(6,LOW);
}

void loop()
{
digitalWrite(4,HIGH); // im Uhrzeigersinn

for(stepCounter = 0; stepCounter < steps; stepCounter++)
{
digitalWrite(5,HIGH);
delayMicroseconds(500);
digitalWrite(5,LOW);
delayMicroseconds(500);
}
delay(1000);

digitalWrite(4,LOW); // gegen den Uhrzeigersinn

for(stepCounter = 0; stepCounter < steps; stepCounter++)
{
digitalWrite(5,HIGH);
delayMicroseconds(500);
digitalWrite(5,LOW);
delayMicroseconds(500);
}
delay(1000);
}`

and the StepMotor works fine. But with the Raspberry it don´t work :/

**Comment by DevTown** [comment]
So I have spoke with the other People of the team an all we can tell is that Adruino and Pi are quiet different and if you want the first you can do is to test your Setup with a Pi. We don't have change something with the calling of the stepper . We do not know your hardware and so we cant tell you exactly what to do. :-( You can play with the settings in the HectorConfig.py.
